### ISSUE TITLE
Refactor the hash class into its own separate file

### ISSUE THREAD

**Issue by ghost** [ArmaAchilles/Hephaestus#16]

**Comment by CreepPork** [comment]
The hashing class is already in a separate class

**Comment by ghost** [comment]
The hashing class that's responsible for the various hashing methods is, but im talking about this: https://github.com/ArmaAchilles/AddonBuilder/blob/d60a7ec02db60254cafb1bcabf9370c98e089198/AddonBuilder/Program.cs#L390-L400
