### ISSUE TITLE
Awareness of being in a git tracked directory

### ISSUE THREAD

**Issue by ghost** [ArmaAchilles/Hephaestus#17]
- Probably won't be relevant in most cases but having the ability for the program to detect that it is in a git tracked directory and alerting the user of such could potentially better prevent people from accidentally committing the builder's ini file in case they decided to put it in the projects directory.

**Comment by CreepPork** [comment]
This could get complicated because if it is placed in subfolders.

**Comment by ghost** [comment]
I'll explore a bit and see if it can be pulled off without tons of code or creating dependencies.

**Comment by CreepPork** [comment]
Dependencies could be ignored if they are bundled with the AddonBuilder itself.

**Comment by ghost** [comment]
Yes but then you also have to worry about the extra surface area for something to break when a major .net framework update gets released, performance concerns, author abandoning the work, quality. I try not to resort to using 3rd party libraries unless I have to. Plus I think it increases the size of the application.

**Comment by CreepPork** [comment]
That's all true but the project is locked to a certain version of .NET

**Comment by ghost** [comment]
You still have to deal with the bloat of having extra libraries.

**Comment by CreepPork** [comment]
Not applicable to version 2.
