### ISSUE TITLE
Consider armake replacing BI's Addon Builder

### ISSUE THREAD

**Issue by CreepPork** [ArmaAchilles/Hephaestus#22]
https://github.com/KoffeinFlummi/armake

**Comment by ghost** [comment]
If it behaves the same way as the addon builder in terms of calling it from the command line and passing arguments it shouldn't be a problem to add support for it in this application.

**Comment by CreepPork** [comment]
It sort of does and it's an open source implementation and has more functionality than BI's Addon Builder.

**Comment by CreepPork** [comment]
Implemented in V2.
