### ISSUE TITLE
Have the user press a key to close the window

### ISSUE THREAD

**Issue by ghost** [ArmaAchilles/Hephaestus#8]
**Description:** If an error occurs in the build or the application cannot build because of an error the window closes to quick in order to be able to read and diagnose the issue. Having the user press a key would also allow the user to verify that everything went correctly even if they did not have an error such as signing.

**Comment by CreepPork** [comment]
There should be a ReadKey for every error

**Comment by CreepPork** [comment]
This would go hand to hand with logging and there is no errors from the BI AddonBuilder because I don't know how to get the error messages from it to my console

**Comment by ghost** [comment]
I ment the errors thrown by this application such as when not being able to find a valid path to something such as the arma 3 game directory.

**Comment by CreepPork** [comment]
Not applicable to version 2.
